//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienDongSoDu
    {
        public int MaBienDong { get; set; }
        public int GiaTriBienDong { get; set; }
        public bool LoaiBienDong { get; set; }
        public int MaNguoiDung { get; set; }
        public System.DateTime Ngay { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
