//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DauGia
    {
        public DauGia()
        {
            this.HinhAnhs = new HashSet<HinhAnh>();
            this.MucNangs = new HashSet<MucNang>();
            this.ThongBaos = new HashSet<ThongBao>();
            this.Loais = new HashSet<Loai>();
        }
    
        public int MaDauGia { get; set; }
        public string MaNguoiBan { get; set; }
        public string MaNguoiMua { get; set; }
        public string TenSanPham { get; set; }
        public string MoTa { get; set; }
        public int GiaBanDau { get; set; }
        public int MucNangToiThieu { get; set; }
        public int GiaCuoi { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string ViTri { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<HinhAnh> HinhAnhs { get; set; }
        public virtual ICollection<MucNang> MucNangs { get; set; }
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
        public virtual ICollection<Loai> Loais { get; set; }
    }
}
