//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loai
    {
        public Loai()
        {
            this.CT_LoaiDauGia = new HashSet<CT_LoaiDauGia>();
        }
    
        public int MaLoai { get; set; }
        public string TenLoai { get; set; }
        public bool TrangThai { get; set; }
        public int MaNguoiDung { get; set; }
        public System.DateTime Ngay { get; set; }
    
        public virtual ICollection<CT_LoaiDauGia> CT_LoaiDauGia { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
