//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DauGiaEntities : DbContext
    {
        public DauGiaEntities()
            : base("name=DauGiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChatRieng> ChatRiengs { get; set; }
        public DbSet<DanhGia> DanhGias { get; set; }
        public DbSet<DauGia> DauGias { get; set; }
        public DbSet<HinhAnh> HinhAnhs { get; set; }
        public DbSet<Loai> Loais { get; set; }
        public DbSet<MucNang> MucNangs { get; set; }
        public DbSet<NguoiDung> NguoiDungs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<ThongBao> ThongBaos { get; set; }
    }
}
