//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public NguoiDung()
        {
            this.ChatRiengs = new HashSet<ChatRieng>();
            this.ChatRiengs1 = new HashSet<ChatRieng>();
            this.DanhGias = new HashSet<DanhGia>();
            this.DanhGias1 = new HashSet<DanhGia>();
            this.MucNangs = new HashSet<MucNang>();
            this.ThongBaos = new HashSet<ThongBao>();
        }
    
        public int MaNguoiDung { get; set; }
        public string HovaTen { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public System.DateTime NgayDangKy { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsApproved { get; set; }
        public int SoDuVi { get; set; }
    
        public virtual ICollection<ChatRieng> ChatRiengs { get; set; }
        public virtual ICollection<ChatRieng> ChatRiengs1 { get; set; }
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual ICollection<DanhGia> DanhGias1 { get; set; }
        public virtual ICollection<MucNang> MucNangs { get; set; }
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
    }
}
