//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangThaiDauGia
    {
        public TrangThaiDauGia()
        {
            this.CT_TrangThai = new HashSet<CT_TrangThai>();
        }
    
        public int MaTrangThai { get; set; }
        public string TenTrangThai { get; set; }
        public System.DateTime Ngay { get; set; }
        public int MaNguoiDung { get; set; }
    
        public virtual ICollection<CT_TrangThai> CT_TrangThai { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
